### ISSUE TITLE
SpanKind support in opencensus-java

### ISSUE THREAD

**Issue by HailongWen** [census-instrumentation/opencensus-java#1054]
https://github.com/census-instrumentation/opencensus-proto/pull/51 added `SpanKind`. We should add the initial support.

Another thread is discussing whether to add `consumer`/`producer` in the type https://github.com/census-instrumentation/opencensus-specs/issues/54. This could be merged after the decision is made.

**Comment by bogdandrutu** [comment]
I think we can add the SpanKind right now and extend later if needed, I would suggest that we update the docs related to HTTP/gRPC span names to not include "Sent." and "Recv." which we will be able to determine from the SpanKind.

Also we need to update the https://github.com/census-instrumentation/opencensus-java/blob/master/impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImpl.java to map not only by name but also by SpanKind.

**Comment by bogdandrutu** [comment]
This is also related https://github.com/census-instrumentation/opencensus-java/pull/1226

**Comment by voidzcy** [comment]
gRPC is trying to migrate to use SpanKind (see https://github.com/grpc/grpc-java/pull/6732), but since Span name is changed, this seems to be a "flip the switch" change for traffic monitoring pipelines. How should we migrate this in gRPC for OSS without breaking open-source users' traffic monitoring pipelines?
