### ISSUE TITLE
examples: show how to change the global configuration/samplers

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-java#1125]
I have been going over the javadocs at https://www.javadoc.io/doc/io.opencensus/opencensus-api/0.12.2 and I can't figure out how to change the global tracer's configuration to make it always sample since am making an integration. I asked for help here and there but no dice.

Some examples of not just changing the sampler for a single span but for the entire global configuration, would be immensely helpful.

**Comment by sebright** [comment]
I think that is controlled with the global [TraceConfig](https://static.javadoc.io/io.opencensus/opencensus-api/0.12.2/io/opencensus/trace/config/TraceConfig.html), for example:

```java
    TraceConfig traceConfig = Tracing.getTraceConfig();
    traceConfig.updateActiveTraceParams(
        traceConfig.getActiveTraceParams().toBuilder().setSampler(Samplers.alwaysSample()).build());
```

/cc @bogdandrutu

**Comment by odeke-em** [comment]
Thank you @sebright! Yes, I looked through all those docs but being unfamiliar with the Java implementation, it was tricky.

**Comment by HailongWen** [comment]
It is the same issue when I tried the examples and got nothing output (#842).
There does exist a [specification](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md) on how to set that in a global/local way. But given that most users might start with examples rather than specification, we should probably explicitly add it in the examples.

**Comment by songy23** [comment]
Fixed with https://opencensus.io/quickstart/java/tracing/.
