### ISSUE TITLE
examples/stats: Views need to be included in the example like the quickstart does

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-java#1154]
Currently examining https://github.com/census-instrumentation/opencensus-java/blob/6c574102fbc5fe050a346167fb68d83c60d58049/examples/src/main/java/io/opencensus/examples/stats/StatsRunner.java

Perhaps let's update it to use Views like the quickstart at OpenCensus.io does https://opencensus.io/java.html

**Comment by songy23** [comment]
The name of this example is a bit misleading now, since it's intended to demonstrate how tags get set into `Scope` and has little to do with stats recording. I'll send a PR to update its name.

For the example that includes view registration and stats recording, please see https://github.com/census-instrumentation/opencensus-java/blob/master/examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java.

A little more background: a few months ago we have both tags and stats under the same package `stats`, that's why this example is called `StatsRunner`. Now since we split the two packages, a more proper name for it should be `TagsRunner`.
