### ISSUE TITLE
can opencensus-java work with opencensus-cpp

### ISSUE THREAD

**Issue by jxd134** [census-instrumentation/opencensus-java#1240]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
v0.14.0 Release

### What JVM are you using (`java -version`)?
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
I want to know can opencensus-cpp can work with opencensus-java, such as opencensus-cpp client call opencensus-java server?
If the answer is yes, i want to know where deal with the trace context send from opencensus-cpp client in the java source.  

### What did you see instead?

**Comment by songy23** [comment]
Hi @jxd134,

For the first qustion, if you're talking about C++/Java gRPC/HTTP client/server that are instrumented by OpenCensus, then the answer is yes, OpenCensus in any language can propagate context to any other language. Not only Java <-> C++, but also Go, Python, PHP, etc. This is because each language needs to implement the serialization and deserialization of trace or tag context (our [specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md)).

Back to your second question, I don't think you need to explicitly deal with the serialized trace context 
from opencensus-cpp in your application code because they should have been taken care of by the library. For example, [gRPC](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/CensusTracingModule.java#L109) will do the serialization and deserialization on trace context for you, when propagating contexts. You can also take a look at our [cross-language interop tests](https://github.com/census-ecosystem/opencensus-experiments/tree/master/integration) if interested.

**Comment by jxd134** [comment]
@songy23 thank you very much.
