### ISSUE TITLE
[Q] Stackdriver trace

### ISSUE THREAD

**Issue by Encraze** [census-instrumentation/opencensus-java#1244]
I have registered Tracing to my stackdriver project and when I run my app I don't see traces at all.
The only way for me to see some (not all) traces is to start spamming method invocations where tracing takes place. After like 5000 calls I might see one or a couple of traces on my gcloud monitor.

A single call never triggers the trace. What am I doing wrong?

Using opencensus 0.14.0 with java 8 and java 10

**Comment by songy23** [comment]
Hi @Encraze , what you have seen is the expected behavior. For trace spans, we have a global default sampling probability of [1e-4](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/config/TraceParams.java#L38) which applies to all spans. As a result it's likely that only one out of 10000 spans will be sampled and exported to Stackdriver Trace, as you see in your gcloud console.

If you want a higher sampling factor, you can either update the [Sampler in global TraceParams](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/config/TraceParams.java#L141), or [directly set sampling factor for a particular span](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/SpanBuilder.java#L118) (which will override the global config for that particular span) that you're interested in.

**Comment by Encraze** [comment]
Ok. Thank you.
