### ISSUE TITLE
Annotations are not properly exported

### ISSUE THREAD

**Issue by reik-wargaming** [census-instrumentation/opencensus-java#1638]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.18.0

### What JVM are you using (`java -version`)?
8

### What did you do?
I use the `ZipkinTraceExporter`. My Spans are annotated like this (kotlin).
`span.addAnnotation("queries", mutableMapOf("foo" to AttributeValue.stringAttributeValue("bar")))`

### What did you expect to see?
Expect to see "foo" and "bar" in the zipkin UI.

### What did you see instead?
Only "queries" is displayed in the UI.
![zipkin_queries](https://user-images.githubusercontent.com/43347670/49807044-68627600-fd59-11e8-8640-bb69623dd73f.png)

JSON looks like this:
```
{
    "traceId": "03482c9ab3611e499fa80db40ffe7bea",
    "id": "91f3cda76d2acdf5",
    "name": "get /api/v1/public/status",
    "timestamp": 1544534826519005,
    "duration": 390751,
    "localEndpoint": {
      "serviceName": "matchmaking-service",
      "ipv4": "10.151.44.7"
    },
    "annotations": [
      {
        "timestamp": 1544534826521429,
        "value": "queries"
      }
    ],
    "tags": {
      "census.status_code": "OK"
    }
  }
```

**Comment by devinsba** [comment]
Annotations in zipkin are not keyed, as you can see in the Span json, an annotation is simply a string associated with a span-local timestamp. If this were to be fixed in census then it would have to do some encoding of that map into a string for use in that annotation, ie: `queries {"foo":"bar"}` but now you have added a non-free action to the tag operation
