### ISSUE TITLE
StackdriverStatsExporter: k8s namespace and container name missing

### ISSUE THREAD

**Issue by mwuertinger** [census-instrumentation/opencensus-java#1751]
### What version of OpenCensus are you using?
0.19.1

### What JVM are you using (`java -version`)?
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

### What did you do?
I'm using `StackdriverStatsExporter.createAndRegister()` in an application running on GKE (1.10.11-gke.1).

### What did you expect to see?
I expect all the labels for `k8s_container` to be populated, see
https://cloud.google.com/monitoring/api/resources#tag_k8s_container

### What did you see instead?
The following labels are empty:
- `namespace_name`
- `container_name`

This makes it very hard to differentiate metrics between multiple applications running within the same GCP project.

Is there a workaround for this?

It would help a lot if it would be possible to set global tags which are appended to all metrics automatically.

**Comment by songy23** [comment]
Hi @mwuertinger, by default `namespace_name` and `container_name` are not visible to the Stackdriver exporter. [Specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/utils/MonitoredResource.md#gcp_gke_container) are:

> The namespace_id and container_name are optional. We cannot get their value from environment variables unless k8s users expose them via the Downward API. See k8s documentation and code sample.

Also see the GKE official code sample [here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/custom-metrics-autoscaling/direct-to-sd/sd_dummy_exporter.go#L71-L91).

In order to get `namespace_name` and `container_name`, you have a few options here:
1. Expose them to containers through [Downwards API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/).
2. Manually create a `Resource`, set `namespace_name` and `container_name` labels, and [pass it to the Stackdriver exporter when creating it](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java#L136).
3. Use the [Kubernetes Operator](https://github.com/census-ecosystem/kubernetes-operator). /cc @fabxc and @bogdandrutu for guidance.

**Comment by songy23** [comment]
Update: @bogdandrutu managed to use [Kubernetes Operator](https://github.com/census-ecosystem/kubernetes-operator) and it worked fine with Stackdriver Trace exporter.

**Comment by mwuertinger** [comment]
Hi @songy23,

thanks for the hints, I will try to use the Downwards API today.
Are there any plans to allow applications to set custom labels like service name?

**Comment by songy23** [comment]
There are two kinds of labels in Stackdriver concept: 
- monitoring resource labels, used to identify the entity that metrics are associated;
- metric labels, used to break down metrics into different dimensions.

Currently with our exporter we only allow setting global resource labels, e.g
```java
  MonitoredResource myResource = MonitoredResource.newBuilder()
                                               .setType("...")
                                               .putLabels("some label", "...")
                                               .build();
    StackdriverStatsExporter.createAndRegister(
        StackdriverStatsConfiguration.builder().setMonitoredResource(myResource).build());
```
Metric labels are transformed from OpenCensus tags + [one additional opencensus_task label](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/stackdriver#what-is-opencensus_task-metric-label-). We don't support adding additional Stackdriver specific metric labels yet.

**Comment by mwuertinger** [comment]
We're now using the following code to get the `MonitoredResource`:
```
    MonitoredResource getMonitoredResource(String containerName) {
        try {
            MonitoredResource.Builder builder = MonitoredResource.newBuilder();
            builder.setType("k8s_container");

            builder.putLabels("container_name", containerName);

            String gcpProjectId = MetadataConfig.getProjectId();
            if (gcpProjectId != null) {
                builder.putLabels("project_id", gcpProjectId);
            }

            String zone = MetadataConfig.getZone();
            if (zone != null) {
                builder.putLabels("location", zone);
            }

            String clusterName = MetadataConfig.getClusterName();
            if (clusterName != null) {
                builder.putLabels("cluster_name", clusterName);
            }

            String namespace = System.getenv("KUBERNETES_NAMESPACE");
            if (namespace != null) {
                builder.putLabels("namespace_name", namespace);
            }

            String hostname = InetAddress.getLocalHost().getHostName();
            builder.putLabels("pod_name", hostname);

            return builder.build();
        } catch (Exception e) {
            log.error("Unable to determine MonitoredResource, falling back to default", e);
            return null;
        }
    }
```

We set the namespace via downward API and just set the container name to the service name within the application. This works fine for our needs right now.

Thanks for your help. We can close this issue.

**Comment by songy23** [comment]
Thanks @mwuertinger for confirmation. Closing this for now, feel free to reopen if you have any follow-up questions.
