### ISSUE TITLE
OcJettyHttpClient doesn't work with HTTPS 

### ISSUE THREAD

**Issue by rghetia** [census-instrumentation/opencensus-java#1756]
OcJettyHttpClient requires two parameter constructor.
HttpClient(HttpClientTransport transport, SslContextFactory sslContextFactory)

### What version of OpenCensus are you using?
0.19.1

**Comment by alexamies** [comment]
The OcJettyHttpClient does work with HTTPS for some versions of the Jetty library because of this [Jetty issue](https://github.com/eclipse/jetty.project/issues/3350), which is considered a regression and is fixed with [this Jetty PR](https://github.com/eclipse/jetty.project/commit/e84feb22b390c0b3793bd1af1e7d85a2967949ff).

**Comment by alexamies** [comment]
Submitted PR to address this
https://github.com/census-instrumentation/opencensus-java/pull/1757

**Comment by songy23** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-java/pull/1757.
