### ISSUE TITLE
Stackdriver metric units missing

### ISSUE THREAD

**Issue by mwuertinger** [census-instrumentation/opencensus-java#1841]
### What version of OpenCensus are you using?
0.20.0

### What JVM are you using (`java -version`)?
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)

### What did you do?
I'm exporting the default gRPC metrics to Stackdriver:
```
StackdriverStatsConfiguration.Builder builder = StackdriverStatsConfiguration.builder();
StackdriverStatsExporter.createAndRegister(builder.build());
RpcViews.registerAllViews();
```

### What did you expect to see?
I expect the units of the metrics to be set accordingly (eg. `By`, `ms`, `1`).

### What did you see instead?
There are no units set for the metrics.

### Workaround
Downgrading to OpenCensus 0.19.1 resolves the issue.

**Comment by songy23** [comment]
Spent some time looking into this issue today. It turns out in v0.20.0 the Stackdriver `MetricDescriptor` is created from time series instead of metric descriptors. 

A bit more background: in Stackdriver there're two ways on creating a `MetricDescriptor`:
1. Explicitly call the `createMetricDescriptor` API (https://cloud.google.com/monitoring/custom-metrics/creating-metrics#call_the_create_method). With this approach `unit` and `description` can be specified for a `MetricDescriptor`. The OpenCensus Stackdriver exporter should have created `MetricDescriptor` with this approach, but somehow in v0.20.0 it didn't work and fall back to the second approach below.
2. Implicitly auto-creating it with uploaded time series (https://cloud.google.com/monitoring/custom-metrics/creating-metrics#auto-creation). `MetricDescriptor`s created in this way won't have units.

For example, when I tried to export the same metric with exporters in 0.19.2 and 0.20.0:

With v0.19.2 I got a `MetricDescriptor`:
```json
{
   "name": "xxx",
   "labels": ["xxx"],
   "metricKind": "CUMULATIVE",
   "valueType": "DISTRIBUTION",
   "description": "test Stackdriver metric",
   "type": "xxx",
   "unit": "ms",
}
```

With v0.20.0 I got a `MetricDescriptor`:
```json
{
 "name": "xxx",
 "labels": ["xxx"],
 "metricKind": "CUMULATIVE",
 "valueType": "DISTRIBUTION",
 "description": "Auto-created custom metric.",
 "type": "xxx"
}
```

Note the descriptor created with v0.20.0 doesn't have a unit. Its description is also different.

**Comment by songy23** [comment]
OK, found the issue is https://github.com/census-instrumentation/opencensus-java/blob/9b2ac2bdc9565517155a9efb1b8581d1a91329dc/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporter.java#L95-L97

This line skips the `createMetricDescriptor` by accident. Sending a PR to fix soon.
