### ISSUE TITLE
Create no-op StatsContextFactory implementation for Stats.getStatsContextFactory()

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#215]
In https://github.com/songy23/instrumentation-java/blob/master/core/src/main/java/com/google/instrumentation/stats/Stats.java:

If Provider.newInstance() returns a null StatsManager, we need to return a no-op StatsContextFactory, instead of just returning null.

**Comment by sebright** [comment]
There is more discussion of this change in #41.

**Comment by zhangkun83** [comment]
No matter which way we go, the stats and tracing API should be consistent in this aspect. At this moment stats returns null, while tracing returns no-op, which is kind of bizarre. @bogdandrutu @dinooliva 

If we go with no-op, we should probably still provide a way to tell if it's no-op, so that the user can do certain optimizations like not sending the headers.

**Comment by adriancole** [comment]
Mentioned elsewhere but i prefer null unless we expect users to routinely
use static factories like this as opposed to dependency injection. If we do
noop it should be very clear that the whole thing is noop as opposed to an
unsampled span for example.

**Comment by sebright** [comment]
#485 added a no-op TagsComponent and TagContext.  We still need a way to distinguish between the two subclasses, though.

**Comment by sebright** [comment]
I opened a new issue for adding a check for no-op implementations: #585
