### ISSUE TITLE
Census keys and values should not crop input

### ISSUE THREAD

**Issue by carl-mastrangelo** [census-instrumentation/opencensus-java#32]
StringUtil seems to discard values that are longer than 255.  This is error prone, because long paths of values can accidentally be trimmed to the same value.  It would be better to just throw an exception up front than silently do the wrong thing.  

The max length is already exposed in TagValue, so it is possible for clients to avoid this error safely.

**Comment by dinooliva** [comment]
That's a good point. We have generally tried to fail silently rather than raise exceptions but it may be worth revisiting that in this case since tag keys and values are generally defined statically.

I'll discuss it with some other folks - anyone have any further thoughts?

**Comment by sebright** [comment]
The new tag key and value classes throw IllegalArgumentException instead of modifying the input:

https://github.com/census-instrumentation/opencensus-java/blob/4598da68238c7f7cc2624af422cec3e17ca2441b/core/src/main/java/io/opencensus/tags/TagKey.java#L146

https://github.com/census-instrumentation/opencensus-java/blob/4598da68238c7f7cc2624af422cec3e17ca2441b/core/src/main/java/io/opencensus/tags/TagValueString.java#L49

**Comment by adriancole** [comment]
since tag keys are made up front, seems reasonable. Tag values happen at
runtime, so this could be tricky to throw on, right?
