### ISSUE TITLE
Add support for multiple library states

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#608]
I think it will be useful to have a enabling level for each of the libraries:

Trace:
 * No-op (should be possible even if the implementation is linked)
 * Only trace ids propagation
 * Normal/Full

Tags:
 * No-op (should be possible even if the implementation is linked)
 * Enable

Stats:
 * No-op (should be possible even if the implementation is linked)
 * Enable

User should be able to configure for example: Trace propagation ids only + Tags enable without any recording.

**Comment by sebright** [comment]
Some notes from discussing this with @bogdandrutu:

- The states will be set programmatically, probably with methods on the Tags, Stats, and Tracing classes.  There should also be methods for getting the state.
- The state for any component can be changed at any time.
- The default for each package is enabled.
- Disabling tagging also disables stats collection.
- Views can be registered at any time, even when stats is disabled.  Disabling stats doesn't clear the registered views, though it does clear any stats that were collected for those views.
- When a view is queried and stats collection is disabled, the result is a ViewData with no stats.
- It may be possible for stats to be recorded with no tags with this sequence of steps, though it is probably okay:
  - Tagging is disabled.
  - The user creates a TagContext, after adding some tags to the builder.
  - Stats and tagging are re-enabled.
  - The user records stats with the TagContext.

**Comment by sebright** [comment]
@bogdandrutu What type of API do you think we should provide?  We could have something like a `setState` method on each component, which is also exposed in the corresponding class containing static methods to access the singleton.  The `setState` methods could each take a different enum type, since the different components have different sets of states.

**Comment by bogdandrutu** [comment]
I think from user perspective they care only about the methods on the static classes (Tracing, Stats, Tags). I don't think we should have an setState on each different component like TagPropagationComponent because we complicate behaviors. Maybe we can have a setTags on the main components TagsComponent, TraceComponent, StatsComponent.

**Comment by bogdandrutu** [comment]
Also I would not initially implement the bullet point:
```Disabling tagging also disables stats collection.```

**Comment by sebright** [comment]
> I think from user perspective they care only about the methods on the static classes (Tracing, Stats, Tags). I don't think we should have an setState on each different component like TagPropagationComponent because we complicate behaviors. Maybe we can have a setTags on the main components TagsComponent, TraceComponent, StatsComponent.

Do you mean `setState`?  I agree.  I only meant the three top level components.

> Also I would not initially implement the bullet point:
Disabling tagging also disables stats collection.

Why?  I don't think we should allow stats collection without tagging and then remove it in the next release, because users could start relying on it.  Or do you think we should support stats without tagging?

**Comment by sebright** [comment]
#659 and #685 add enabled/disabled states for tagging.

**Comment by sebright** [comment]
#712 added the API for enabling/disabling stats collection.

**Comment by sebright** [comment]
I discussed this with @bogdandrutu, @zhangkun83, @dinooliva, and @songy23.  We decided to deprecate the setState methods, since there isn't a definite use case yet, and it could lead to inconsistent stats.  For example, the number of ended RPCs could be higher than the number of started RPCs if stats collection is enabled at a bad time.  We will still implement the setState methods, but prevent them from updating the state after the state has been read.  This behavior will still allow users to set the state during initialization, but it will also allow other libraries, such as gRPC, to check the state once and make optimizations based on the result.  We could expose that behavior as an "unsafe" method later, if necessary.

**Comment by sebright** [comment]
There are a few more relevant comments in #673.

**Comment by songy23** [comment]
Shall we close this issue now? @bogdandrutu @sebright

**Comment by sebright** [comment]
I think we can close this for now, since we don't currently have a need for setState.
