### ISSUE TITLE
Decide whether to add  a no-op ViewManager.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#614]
Currently, `Stats.getViewManager()` returns null if no implementation is available.  We could instead return a no-op ViewManager, for consistency with `Stats.getStatsRecorder()` and most of the tracing classes.  However, a no-op ViewManager is much less useful than a no-op StatsRecorder, because the ViewManager isn't used by instrumented code.  The ViewManager is used by code that may already need to check whether stats collection is enabled.  That code would need to call an `isNoop()` method instead of checking for null.

I looked at the other packages quickly, and the only other classes that use null instead of no-op implementations are `RunningSpanStore` and `SampledSpanStore`.

EDIT: [ViewManager](https://github.com/census-instrumentation/opencensus-java/blob/master/core/src/main/java/io/opencensus/stats/ViewManager.java) contains the methods for registering views and querying the stats collected for those views.

**Comment by songy23** [comment]
Let's say if we had a no-op ViewManager, when users called [ViewManager.getView()](https://github.com/census-instrumentation/opencensus-java/blob/master/core/src/main/java/io/opencensus/stats/ViewManager.java#L34), a no-op `ViewData` needs to be returned (since if getView() returns null in this case, users still need to perform a null check). So my question is, if we add a no-op `ViewManager`, how do we define a meaningful no-op `ViewData`?

**Comment by sebright** [comment]
One solution is to store the views that are registered, so that they can be included in ViewDatas, and then return ViewDatas that have no stats.  That behavior would be very similar to the behavior when stats collection is disabled at runtime with #608.

**Comment by sebright** [comment]
I'll work on a PR for a no-op ViewManager.

**Comment by sebright** [comment]
I made a PR: #677
