### ISSUE TITLE
Check for null status/annotations/etc in Span

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#785]
We should check for nulls in the Span (blankspan, noopspan, etc.);

**Comment by sebright** [comment]
[NullPointerTester](https://static.javadoc.io/com.google.guava/guava-testlib/19.0/com/google/common/testing/NullPointerTester.html) might be useful for checking all of the classes in the API.

**Comment by dvfeinblum** [comment]
Hey @sebright. I'm looking to get under opencensus's hood and was wondering if this would be a good first issue for a would-be contributor! Thanks.

**Comment by sebright** [comment]
Yes, I think this is a good first issue.  Let us know if you have any questions!

**Comment by dvfeinblum** [comment]
As it so happens, I do have a couple questions:

1. Is it safe to assume that adding null checking to the abstract `Span` class will trickle down and cover the actual Spans themselves (blankspan, noopspan, etc.). Basically, is this the right place to add [this](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/Span.java) checking?

2. When the original comment says that "[w]e should check for nulls in the Span," what are they specifically referring to? Is this the sort of thing that a few `@NonNull` tags in the implementations could rectify or is there something more complex implied here?

Hope these questions make sense; I'm a bit unfamiliar with the codebase and the original comment is a little sparse with information. Any other helpful hints you have are more than welcome, too. Thanks!

**Comment by sebright** [comment]
> Is it safe to assume that adding null checking to the abstract Span class will trickle down and cover the actual Spans themselves (blankspan, noopspan, etc.). Basically, is this the right place to add this checking?

I think that the null checks should be added in all of the methods that implement the methods in Span.  For example, [Span.putAttribute](https://github.com/census-instrumentation/opencensus-java/blob/8ff7ff9abec6b7abe95391fb450d99866c6a2c3a/api/src/main/java/io/opencensus/trace/Span.java#L95) is implemented in Span, BlankSpan, and SpanImpl, so all three implementations should check that the key and value are not null.

> When the original comment says that "[w]e should check for nulls in the Span," what are they specifically referring to? Is this the sort of thing that a few `@NonNull` tags in the implementations could rectify or is there something more complex implied here?

This issue is about ensuring that the arguments are non-null at runtime.  Actually, the project is already using the Checker Framework to ensure that all null annotations are consistent, and it treats unannotated parameters as `@NonNull`.  However, it is still necessary to add runtime checks to API methods to ensure that null values aren't passed in from external code, which might not respect the annotations.

Most of the project uses Guava's `Preconditions.checkNotNull` to check for null, though we've removed most uses of Guava from the API to handle issue #1081.  The `api` directory now uses `io.opencensus.internal.Utils.checkNotNull` instead, which is internal to the API.

**Comment by dvfeinblum** [comment]
Ahhh, okay this makes perfect sense to me now. Thanks so much for the thorough answer. I'm gonna take a crack at this later today!

**Comment by songy23** [comment]
Should this be closed by https://github.com/census-instrumentation/opencensus-java/pull/1150?

**Comment by songy23** [comment]
I think https://github.com/census-instrumentation/opencensus-java/pull/1150 should have covered everything in this issue, but want confirm with @bogdandrutu and @sebright if there's any work left :)

**Comment by sebright** [comment]
Yes, I think this can be closed.  I can also make a PR to check for null in `Span.end`, to finish up null checking in the Span API.
