### ISSUE TITLE
ExportComponentImpl.getRunningSpanStore() and getSampledSpanStore() can return null.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#914]
#679 made the `NoopExportComponent` return no-op implementations for the `RunningSpanStore` and `SampledSpanStore` and removed the `Nullable` annotations on their getters.  However, `ExportComponentImpl.createWithoutInProcessStores(...)` still creates an `ExportComponent` that has a null `RunningSpanStore` and `SampledSpanStore`.  We should make the implementation always return non-null values to be consistent with the no-op classes.

**Comment by HailongWen** [comment]
I'll handle it.

**Comment by HailongWen** [comment]
We cannot directly return a no-op in `ExportComponentImpl` since it returns real implementation classes `RunningSpanStoreImpl` and `SampledSpanStoreImpl`.
 
I am thinking about 2 options:
1. re-apply the `@Nullable` to original `ExportComponent`. Need to define the behavior for `null` in javadoc clearly.
2. implementing no-op `NoopRunningSpanStoreImpl` and `NoopSampledSpanStoreImpl`. Also need to consider providing an API to tell whether the `ExportComponentImpl` supports `inProgcessStores` or not since we cannot tell it by judging nullness (either by exposing these 2 classes directly, or by adding a new API e.g. `isSupportInProcessStores`).
 
@sebright @bogdandrutu what do you think?

**Comment by sebright** [comment]
@HailongWen I prefer option (2), because returning no-op objects is more consistent with other parts of the stats and tracing API.  Where would isSupportInProcessStores be called?  If it is only needed by the implementation, then we could add it to RunningSpanStoreImpl and SampledSpanStoreImpl.  Then we could make each of those classes abstract, with functional and no-op subclasses.
